using System;

public enum MovePresetProperty : byte {
	MAX_NATURAL_SPEED,
	DRAG,
	JUMP_HEIGHT,
	MOMENTUM_GROWTH,
	MINIMUM_MOMENTUM_TO_STOP,
	GRAVITY_ACCELERATION,
	GRAVITY_MAX_ACCELERATION_TIME,
	MAX_RUNNING_MOMENTUM,
	RUN_MOMENTUM_GROWTH,
	RUN_MOMENTUM_DECREASE,
	POV_ADJUSTMENT,
	MAXIMUM_IMPACT_ANGLE_TOLERANCE,
	MAXIMUM_ALLOWED_MOMENTUM_AFTER_IMPACT
}